/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../archiver.hpp"
/* Header for class ua_chillcrew_archivec_core_ArchivecCore */

#ifndef _Included_ua_chillcrew_archivec_core_ArchivecCore
#define _Included_ua_chillcrew_archivec_core_ArchivecCore
#ifdef __cplusplus
extern "C" {
#endif

Archiver *archiver = new Archiver();

static jclass java_util_ArrayList;
static jmethodID java_util_ArrayList_;
jmethodID java_util_ArrayList_size;
jmethodID java_util_ArrayList_get;
jmethodID java_util_ArrayList_add;

void init(JNIEnv *);

void array_list_to_vector(JNIEnv *, std::vector<uint32_t> &, jobject);

/*
 * Class:     ua_chillcrew_archivec_core_ArchivecCore
 * Method:    extractFilesNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_ua_chillcrew_archivec_core_ArchivecCore_extractFilesNative
        (JNIEnv *, jclass, jstring, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
